using System;
using System.Linq;
using EulerPages.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace EulerPages.Data
{
    public class DbInitializer
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new ProblemContext(
                serviceProvider.GetRequiredService<DbContextOptions<ProblemContext>>()))
            {
                if (context.Problems.Any())
                {
                    return;
                }

                var problems = new Problem[]
                    {
                        new Problem
                        {
                            ProblemId = 1,
                            Answer = 0,
                            Question =
                            @"If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

                            Find the sum of all the multiples of 3 or 5 below 1000.",
                            Title = "Multiples of 3 and 5"
                        },
                        new Problem
                        {
                            ProblemId = 2,
                            Answer = 0,
                            Question =
                            @"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

                            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

                            By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.",
                            Title = "Even Fibonacci numbers"
                        },
                        new Problem
                        {
                            ProblemId = 3,
                            Answer = 0,
                            Question =
                            @"The prime factors of 13195 are 5, 7, 13 and 29.

                            What is the largest prime factor of the number 600851475143 ?",
                            Title = "Largest prime factor"
                        }
                    };

                foreach (var p in problems)
                {
                    context.Problems.Add(p);
                }

                context.SaveChanges();

                var solutions = new Solution[]
                {
                    new Solution
                    {
                        ProblemId = 1,
                        Score = 10,
                        Text = @"Model solution... ",
                        Code = @"Model code..."
                    }
                };

                foreach (var s in solutions)
                {
                    context.Solutions.Add(s);
                }

                context.SaveChanges();
            }
        }
    }
}
