using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace EulerPages.Models
{
    public class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new ProblemContext(
                serviceProvider.GetRequiredService<DbContextOptions<ProblemContext>>()))
            {
                if (context.Problem.Any())
                {
                    return;
                }

                context.Problem.AddRange(
                    new Problem
                    {
                        Answer = 0,
                        Question =
                        @"If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

                        Find the sum of all the multiples of 3 or 5 below 1000.",
                        Solution = "",
                        Solved = false,
                        Title = "Multiples of 3 and 5"
                    },
                    new Problem
                    {
                        Answer = 0,
                        Question =
                        @"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

                        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

                        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.",
                        Solution = "",
                        Solved = false,
                        Title = "Even Fibonacci numbers"
                    }
                );

                context.SaveChanges();
            }
        }
    }
}
